version: "3.8"

services:
  backend:
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - SPRING_PROFILES_ACTIVE=prod
