# application.yml  
spring:
  profiles:
    active: dev # 这里可以设置默认激活的Profile，比如开发环境
    group:
      "dev": devDB,devRedis,devMVC
      "pro": proDB,proRedis,proMVC
      "test": testDB,testRedis,testMVC
# 开启日志
mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lz.pojo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #开启驼峰命名
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  #  启动Banner是在应用程序启动时打印的MyBatis-Plus的Logo和版本信息，默认情况下是启用的。
  global-config:
    banner: true
  
    

#logging:
#  config: src/main/resources/custom-logback.xml
logging:
  # 设置日志组
  group:
    # 自定义组名，设置当前组中所包含的包
    ebank: com.lz.controller
  level:
    com:
      lz:
        mapper: debug
        service: info
        controller: info
        config: debug
    root: INFO
    org.springframework.data.convert.CustomConversions: ERROR
    org.springframework.data.mongodb: info
    ebank: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n "
#  file:
#    name: server.log
#  logback:
#    rollingpolicy:
#      max-file-size: 4KB
#      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log